import React, { useCallback, useEffect, useState } from "react";
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { Colors } from "../../theme";
import { adminAttendanceLeaveServices } from "../../services/adminAttendanceLeaveServices";
import { Button, Field, State } from "../../components/AttendanceLeavePrimitives";

export default function AdminLeaveApprovals() {
 const [status,setStatus]=useState<"PENDING"|"APPROVED"|"REJECTED">("PENDING");const [requests,setRequests]=useState<any[]>([]);const [remarks,setRemarks]=useState<Record<string,string>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [processing,setProcessing]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await adminAttendanceLeaveServices.getLeaveRequests({status});setRequests(Array.isArray(r)?r:[]);}catch(e:any){setError(e?.response?.data?.message??e?.message??"Unable to load leave requests.");}finally{setLoading(false);}},[status]);
 useEffect(()=>{load();},[load]);
 const decide=async(id:string,decision:"APPROVED"|"REJECTED")=>{setProcessing(id);try{await adminAttendanceLeaveServices.decideLeave({leaveId:id,decision,remarks:remarks[id]??""});Alert.alert("Updated","Leave request updated.");await load();}catch(e:any){Alert.alert("Error",e?.response?.data?.message??e?.message??"Unable to update request.");}finally{setProcessing("");}};
 return <SafeAreaView style={styles.safe}><State loading={loading} error={error} retry={load}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Leave Approvals</Text><Text style={styles.subtitle}>Review teacher and staff leave requests</Text>{(["PENDING","APPROVED","REJECTED"] as const).map(s=><Button key={s} title={s} secondary={status!==s} onPress={()=>setStatus(s)}/>)}{requests.length===0?<Text style={styles.empty}>No {status.toLowerCase()} requests.</Text>:requests.map(r=>{const id=String(r.id??r.leaveId);const person=r.teacher??r.staff??r.user;return <View style={styles.card} key={id}><Text style={styles.name}>{person?.name??r.employeeName??r.teacherName??"Staff member"}</Text><Text style={styles.meta}>{r.fromDate??r.startDate??"—"} to {r.toDate??r.endDate??"—"}</Text><Text style={styles.reason}>{r.reason??r.leaveReason??"No reason provided"}</Text><Field label="Remarks" value={remarks[id]??""} onChangeText={(v:string)=>setRemarks(p=>({...p,[id]:v}))}/>{status==="PENDING"&&<><Button title={processing===id?"Processing...":"Approve"} disabled={processing===id} onPress={()=>decide(id,"APPROVED")}/><Button title="Reject" secondary disabled={processing===id} onPress={()=>decide(id,"REJECTED")}/></>}</View>;})}</ScrollView></State></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.background},content:{padding:16,paddingBottom:40},title:{fontSize:26,fontWeight:"800",color:Colors.text},subtitle:{color:Colors.textSecondary,marginTop:5,marginBottom:20},card:{borderWidth:1,borderColor:Colors.border,borderRadius:12,padding:14,marginBottom:12},name:{fontSize:16,fontWeight:"800",color:Colors.text},meta:{color:Colors.textSecondary,marginTop:5},reason:{color:Colors.text,marginVertical:10},empty:{color:Colors.textSecondary,marginTop:20}});
